# Generated by Django 4.2.7 on 2023-12-01 14:52

from django.db import migrations, models

def set_auto_increment_start(apps, schema_editor):
    MyModel = apps.get_model('books', 'Author')
    schema_editor.execute("SELECT setval('books_author_id_seq', 651, false)")


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.RunPython(set_auto_increment_start),
    ]
