# Generated by Django 4.2.7 on 2023-12-01 16:45

from django.db import migrations, models

def set_auto_increment_start(apps, schema_editor):
    schema_editor.execute("SELECT setval('books_author_id_seq', 681, false)")
    schema_editor.execute("SELECT setval('books_location_id_seq', 39, false)")
    schema_editor.execute("SELECT setval('books_language_id_seq', 4, false)")
    schema_editor.execute("SELECT setval('books_type_id_seq', 40, false)")

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.RunPython(set_auto_increment_start),
    ]
