# Generated by Django 4.2.7 on 2023-12-01 16:52

from django.db import migrations, models

def set_auto_increment_start(apps, schema_editor):
    schema_editor.execute("SELECT setval('books_book_id_seq', 2544, false)")


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.RunPython(set_auto_increment_start),
    ]
