# Generated by Django 4.2.7 on 2023-12-01 17:16

from django.db import migrations, models

def set_auto_increment_start(apps, schema_editor):
    schema_editor.execute("SELECT setval('main_user_id_seq', 8, false)")
    schema_editor.execute("SELECT setval('main_user_groups_id_seq', 4, false)")



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
